import { SvgImage } from './image'
import { HomeInfo, HomePet, HomePlot, HomeQueryResult } from '../types'
import {
  flattenHomePlots,
  getGuardHomePets,
  getHomeEggPets,
  getHomePlotName,
  getHomeStealLeft,
  getLivingHomePets,
  getPlantedHomePlots,
  getRipeHomePlots,
  isEmptyHomePlot,
} from '../utils/home'
import { formatDateTime } from '../utils/time'

const WIDTH = 920
const PADDING_X = 40
const MAX_PET_CARDS = 10
const PLANT_GRID_COLUMNS = 3

export function renderHomeSvgImage(result: HomeQueryResult, timezoneOffset: number): SvgImage {
  const home = result.home
  const overview = home.overview || {}
  const homeName = overview.homeName || '未命名家园'
  const livingPets = getLivingHomePets(home)
  const guardPets = getGuardHomePets(home)
  const eggs = getHomeEggPets(home)
  const plots = flattenHomePlots(home)
  const plantedPlots = getPlantedHomePlots(home)
  const ripePlots = getRipeHomePlots(home)
  const stealLeft = plantedPlots.reduce((total, plot) => total + getHomeStealLeft(plot), 0)
  const content: string[] = []

  renderHeader(content, result, homeName, timezoneOffset)

  let y = 178
  y = renderStats(content, y, [
    ['家园等级', formatValue(overview.homeLevel, 'Lv.')],
    ['舒适度', formatNumber(overview.comfortLevel)],
    ['精灵', `${livingPets.length} 居住 / ${guardPets.length} 守护`],
    ['作物', `${ripePlots.length} 成熟 / ${plots.length || home.plantCount || 0} 地块`],
  ])

  y = renderPetSection(content, y, '居住精灵', livingPets)

  if (guardPets.length) {
    y = renderGuardPetSection(content, y, guardPets)
  }

  if (eggs.length) {
    y = renderPetSection(content, y, '待拾取蛋', eggs, 6, pet => `${pet.name || '未知精灵'}的蛋`)
  }

  y = renderPlantSection(content, y, home, plots, plantedPlots, ripePlots, stealLeft)

  if (result.warning) {
    y = renderNotice(content, y, result.warning)
  }

  const height = y + 54
  content.push(`<text x="${PADDING_X}" y="${height - 22}" font-size="14" font-family="${FONT_FAMILY}" fill="#6f7668">Generated by koishi-plugin-roco-world-merchant</text>`)

  return {
    width: WIDTH,
    height,
    svg: `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${WIDTH}" height="${height}" viewBox="0 0 ${WIDTH} ${height}">
${renderDefs()}
<rect width="${WIDTH}" height="${height}" rx="26" fill="url(#home-bg)"/>
<circle cx="820" cy="48" r="170" fill="#f5d487" opacity="0.22"/>
<circle cx="96" cy="${height - 20}" r="150" fill="#93b76f" opacity="0.13"/>
${content.join('\n')}
</svg>`,
  }
}

function renderDefs() {
  return `<defs>
  <linearGradient id="home-bg" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0%" stop-color="#f8f0dc"/>
    <stop offset="54%" stop-color="#f2ead4"/>
    <stop offset="100%" stop-color="#e6eed8"/>
  </linearGradient>
  <linearGradient id="home-header" x1="0" y1="0" x2="1" y2="0">
    <stop offset="0%" stop-color="#315f43"/>
    <stop offset="58%" stop-color="#527d47"/>
    <stop offset="100%" stop-color="#b8863e"/>
  </linearGradient>
  <filter id="card-shadow" x="-6%" y="-12%" width="112%" height="130%">
    <feDropShadow dx="0" dy="8" stdDeviation="8" flood-color="#4b593e" flood-opacity="0.13"/>
  </filter>
</defs>`
}

function renderHeader(content: string[], result: HomeQueryResult, homeName: string, timezoneOffset: number) {
  content.push(`<rect x="0" y="0" width="${WIDTH}" height="146" rx="26" fill="url(#home-header)"/>`)
  content.push(`<path d="M0 118 C150 86 260 154 410 118 C590 74 710 160 920 96 L920 146 L0 146 Z" fill="#f6edcf" opacity="0.16"/>`)
  content.push(`<text x="${PADDING_X}" y="54" font-size="28" font-family="${FONT_FAMILY}" fill="#ffffff" font-weight="800">家园查询</text>`)
  content.push(`<text x="${PADDING_X}" y="94" font-size="34" font-family="${FONT_FAMILY}" fill="#fff6d8" font-weight="800">${escapeXml(truncate(homeName, 18))}</text>`)
  content.push(`<text x="590" y="58" font-size="16" font-family="${FONT_FAMILY}" fill="#edf6dc">UID：${escapeXml(result.uid)}</text>`)
  content.push(`<text x="590" y="88" font-size="16" font-family="${FONT_FAMILY}" fill="#edf6dc">来源：${formatOrigin(result.origin)}</text>`)
  content.push(`<text x="590" y="118" font-size="16" font-family="${FONT_FAMILY}" fill="#edf6dc">更新时间：${escapeXml(formatDateTime(result.fetchedAt, timezoneOffset))}</text>`)
}

function renderStats(content: string[], y: number, stats: [string, string][]) {
  const cardWidth = 198
  const gap = 16

  stats.forEach(([label, value], index) => {
    const x = PADDING_X + index * (cardWidth + gap)
    content.push(`<rect x="${x}" y="${y}" width="${cardWidth}" height="82" rx="18" fill="#fffdf5" stroke="#dfd2af" filter="url(#card-shadow)"/>`)
    content.push(`<text x="${x + 18}" y="${y + 30}" font-size="15" font-family="${FONT_FAMILY}" fill="#7c856f">${escapeXml(label)}</text>`)
    content.push(`<text x="${x + 18}" y="${y + 60}" font-size="22" font-family="${FONT_FAMILY}" fill="#2f3f31" font-weight="800">${escapeXml(truncate(value, 14))}</text>`)
  })

  return y + 110
}

function renderPetSection(
  content: string[],
  y: number,
  title: string,
  pets: HomePet[],
  max = MAX_PET_CARDS,
  formatter = formatPet,
) {
  if (!pets.length) {
    return y
  }

  y = renderSectionTitle(content, y, title, `${pets.length} 项`)
  const visible = pets.slice(0, max)
  const cardWidth = 406
  const cardHeight = 146
  const gapX = 18
  const gapY = 18

  visible.forEach((pet, index) => {
    const col = index % 2
    const row = Math.floor(index / 2)
    const x = PADDING_X + col * (cardWidth + gapX)
    const cardY = y + row * (cardHeight + gapY)
    const accent = pet.hasEgg ? '#d89439' : pet.status === 1704 ? '#7d8d9b' : '#6e9b57'
    const inspiration = getPetInspiration(pet)
    const displayName = formatter(pet) || pet.name || '未知精灵'

    content.push(`<rect x="${x}" y="${cardY}" width="${cardWidth}" height="${cardHeight}" rx="18" fill="#fffdf6" stroke="#ded3b5" filter="url(#card-shadow)"/>`)
    renderPetAvatar(content, x + 18, cardY + 16, 72, pet)
    content.push(`<text x="${x + 104}" y="${cardY + 35}" font-size="20" font-family="${FONT_FAMILY}" fill="#2f392f" font-weight="800">${escapeXml(truncate(displayName, 10))}</text>`)
    content.push(`<rect x="${x + 326}" y="${cardY + 18}" width="58" height="24" rx="12" fill="#e8d08b"/>`)
    content.push(`<text x="${x + 355}" y="${cardY + 35}" font-size="13" font-family="${FONT_FAMILY}" fill="#5b461a" font-weight="800" text-anchor="middle">${escapeXml(pet.level != null ? `Lv.${pet.level}` : 'Lv.?')}</text>`)
    renderPetBadges(content, x + 104, cardY + 50, pet)
    content.push(`<text x="${x + 18}" y="${cardY + 116}" font-size="14" font-family="${FONT_FAMILY}" fill="#47513f" font-weight="700">${escapeXml(inspiration.label)}</text>`)
    content.push(`<rect x="${x + 18}" y="${cardY + 126}" width="${cardWidth - 36}" height="8" rx="4" fill="#ebe2cc"/>`)
    content.push(`<rect x="${x + 18}" y="${cardY + 126}" width="${Math.round((cardWidth - 36) * inspiration.progress / 100)}" height="8" rx="4" fill="${accent}"/>`)
  })

  const rows = Math.ceil(visible.length / 2)
  y += rows * (cardHeight + gapY)
  if (pets.length > visible.length) {
    content.push(`<text x="${PADDING_X}" y="${y + 12}" font-size="14" font-family="${FONT_FAMILY}" fill="#7c856f">还有 ${pets.length - visible.length} 项未展示</text>`)
    y += 24
  }

  return y + 16
}

function renderGuardPetSection(content: string[], y: number, pets: HomePet[]) {
  if (!pets.length) {
    return y
  }

  y = renderSectionTitle(content, y, '守护精灵', `${pets.length} 项`)
  const cardWidth = 194
  const cardHeight = 118
  const gapX = 18
  const gapY = 18
  const columns = 4

  pets.forEach((pet, index) => {
    const col = index % columns
    const row = Math.floor(index / columns)
    const x = PADDING_X + col * (cardWidth + gapX)
    const cardY = y + row * (cardHeight + gapY)

    content.push(`<rect x="${x}" y="${cardY}" width="${cardWidth}" height="${cardHeight}" rx="18" fill="#fffdf6" stroke="#ded3b5" filter="url(#card-shadow)"/>`)
    renderPetAvatar(content, x + 61, cardY + 16, 72, pet, '#f0ead4', '#d2bd8d')
    content.push(`<text x="${x + cardWidth / 2}" y="${cardY + 101}" font-size="17" font-family="${FONT_FAMILY}" fill="#2f392f" font-weight="800" text-anchor="middle">${escapeXml(truncate(pet.name || '未知精灵', 8))}</text>`)
  })

  const rows = Math.ceil(pets.length / columns)
  return y + rows * cardHeight + Math.max(0, rows - 1) * gapY + 22
}

function renderPetAvatar(
  content: string[],
  x: number,
  y: number,
  size: number,
  pet: HomePet,
  fill = '#efe6cb',
  stroke = '#d7c8a3',
) {
  const center = x + size / 2
  content.push(`<circle cx="${center}" cy="${y + size / 2}" r="${size / 2}" fill="${fill}" stroke="${stroke}" stroke-width="2"/>`)
  content.push(`<text x="${center}" y="${y + size / 2 + 3}" font-size="${Math.round(size * 0.44)}" font-family="${FONT_FAMILY}" fill="#8a7d58" font-weight="800" text-anchor="middle" dominant-baseline="middle">${escapeXml((pet.name || '?').slice(0, 1))}</text>`)
  if (pet.iconUrl) {
    content.push(`<image x="${x}" y="${y}" width="${size}" height="${size}" preserveAspectRatio="xMidYMid meet" href="${escapeXml(pet.iconUrl)}"/>`)
  }
}

function renderPetBadges(content: string[], x: number, y: number, pet: HomePet) {
  const badges = [
    formatGenderText(pet.gender),
    formatMutation(pet),
    pet.feedRound != null ? `轮次 ${pet.feedRound}` : '',
  ].filter(Boolean)
  let cursor = x
  badges.slice(0, 4).forEach((badge) => {
    const width = Math.max(38, Math.min(92, 18 + badge.length * 12))
    content.push(`<rect x="${cursor}" y="${y}" width="${width}" height="22" rx="11" fill="#f0eadb" stroke="#d6c8a8"/>`)
    content.push(`<text x="${cursor + width / 2}" y="${y + 15}" font-size="12" font-family="${FONT_FAMILY}" fill="#5a604f" font-weight="700" text-anchor="middle">${escapeXml(badge)}</text>`)
    cursor += width + 8
  })
}

function renderPlantSection(
  content: string[],
  y: number,
  home: HomeInfo,
  plots: HomePlot[],
  plantedPlots: HomePlot[],
  ripePlots: HomePlot[],
  stealLeft: number,
) {
  y = renderSectionTitle(content, y, '种植园', home.plantUnlocked ? `${plantedPlots.length}/${plots.length || home.plantCount || 0} 已种植` : '未解锁')

  if (!home.plantUnlocked) {
    content.push(`<rect x="${PADDING_X}" y="${y}" width="${WIDTH - PADDING_X * 2}" height="48" rx="16" fill="#fffdf6" stroke="#ded3b5"/>`)
    content.push(`<text x="${PADDING_X + 20}" y="${y + 30}" font-size="17" font-family="${FONT_FAMILY}" fill="#6f7668">种植园暂未解锁或数据源未返回种植信息。</text>`)
    return y + 72
  }

  const displayPlots = plots.length ? plots : plantedPlots

  content.push(`<rect x="${PADDING_X}" y="${y}" width="${WIDTH - PADDING_X * 2}" height="52" rx="18" fill="#eff7e7" stroke="#c8d9b3"/>`)
  content.push(`<text x="${PADDING_X + 20}" y="${y + 33}" font-size="17" font-family="${FONT_FAMILY}" fill="#38553a" font-weight="700">已成熟 ${ripePlots.length} 块，剩余可偷取 ${stealLeft} 次</text>`)
  y += 70

  if (!displayPlots.length) {
    content.push(`<rect x="${PADDING_X}" y="${y}" width="${WIDTH - PADDING_X * 2}" height="48" rx="16" fill="#fffdf6" stroke="#ded3b5"/>`)
    content.push(`<text x="${PADDING_X + 20}" y="${y + 30}" font-size="17" font-family="${FONT_FAMILY}" fill="#6f7668">当前没有可展示的种植地块。</text>`)
    return y + 72
  }

  const gapX = 16
  const gapY = 18
  const cardWidth = Math.floor((WIDTH - PADDING_X * 2 - gapX * (PLANT_GRID_COLUMNS - 1)) / PLANT_GRID_COLUMNS)
  const cardHeight = 154

  displayPlots.forEach((plot, index) => {
    const col = index % PLANT_GRID_COLUMNS
    const row = Math.floor(index / PLANT_GRID_COLUMNS)
    const x = PADDING_X + col * (cardWidth + gapX)
    const cardY = y + row * (cardHeight + gapY)
    const empty = isEmptyHomePlot(plot)
    const ripe = isPlotRipe(plot)
    const fill = ripe ? '#fff7e4' : '#fffdf6'
    const stroke = ripe ? '#ddb76f' : '#ded3b5'
    const progress = getPlotProgress(plot)
    const title = getHomePlotName(plot)
    const status = empty ? '空地' : ripe ? '已成熟' : '生长中'
    const statusFill = empty ? '#d7c8a3' : ripe ? '#e7bd73' : '#cfe3bc'
    const statusTextFill = empty ? '#6f664c' : ripe ? '#7a4e15' : '#38553a'

    content.push(`<rect x="${x}" y="${cardY}" width="${cardWidth}" height="${cardHeight}" rx="18" fill="${fill}" stroke="${stroke}" filter="url(#card-shadow)"/>`)
    content.push(`<text x="${x + cardWidth - 18}" y="${cardY + 25}" font-size="13" font-family="${FONT_FAMILY}" fill="#9b927d" font-weight="700" text-anchor="end">#${index + 1}</text>`)
    renderPlantIcon(content, x + 18, cardY + 18, 58, plot, ripe, progress)
    content.push(`<text x="${x + 90}" y="${cardY + 35}" font-size="18" font-family="${FONT_FAMILY}" fill="#2f392f" font-weight="800">${escapeXml(truncate(title, 8))}</text>`)
    content.push(`<rect x="${x + 90}" y="${cardY + 48}" width="64" height="24" rx="12" fill="${statusFill}"/>`)
    content.push(`<text x="${x + 122}" y="${cardY + 65}" font-size="13" font-family="${FONT_FAMILY}" fill="${statusTextFill}" font-weight="800" text-anchor="middle">${escapeXml(status)}</text>`)
    content.push(`<text x="${x + 18}" y="${cardY + 98}" font-size="14" font-family="${FONT_FAMILY}" fill="${ripe ? '#a36321' : '#65705d'}">${escapeXml(empty ? '等待种植' : formatPlotRemain(plot))}</text>`)
    content.push(`<text x="${x + 18}" y="${cardY + 121}" font-size="14" font-family="${FONT_FAMILY}" fill="#65705d">${escapeXml(empty ? '暂无作物' : `产量 ${formatUnknown(plot.harvestNum)} | 可偷 ${getHomeStealLeft(plot)}`)}</text>`)
    content.push(`<rect x="${x + 18}" y="${cardY + 134}" width="${cardWidth - 36}" height="8" rx="4" fill="#eadfc7"/>`)
    content.push(`<rect x="${x + 18}" y="${cardY + 134}" width="${Math.round((cardWidth - 36) * progress / 100)}" height="8" rx="4" fill="${ripe ? '#68c688' : '#89d891'}"/>`)
  })

  const rows = Math.ceil(displayPlots.length / PLANT_GRID_COLUMNS)
  y += rows * cardHeight + Math.max(0, rows - 1) * gapY

  return y + 18
}

function renderPlantIcon(
  content: string[],
  x: number,
  y: number,
  size: number,
  plot: HomePlot,
  ripe: boolean,
  progress: number,
) {
  const centerX = x + size / 2
  const centerY = y + size / 2
  const empty = isEmptyHomePlot(plot)

  content.push(`<circle cx="${centerX}" cy="${centerY}" r="${size / 2}" fill="#f2ead5" stroke="#d4c59d" stroke-width="2"/>`)

  if (empty) {
    content.push(`<ellipse cx="${centerX}" cy="${y + size * 0.66}" rx="${size * 0.28}" ry="${size * 0.12}" fill="#c2a06c"/>`)
    content.push(`<path d="M${centerX - 8} ${centerY + 2} C${centerX - 8} ${centerY - 9}, ${centerX + 8} ${centerY - 9}, ${centerX + 8} ${centerY + 2}" fill="none" stroke="#8ea15b" stroke-width="3" stroke-linecap="round"/>`)
    return
  }

  const palette = getPlantPalette(plot, ripe)
  content.push(`<path d="M${centerX} ${centerY + 16} C${centerX - 4} ${centerY + 4}, ${centerX - 2} ${centerY - 5}, ${centerX} ${centerY - 14}" fill="none" stroke="#5d8c54" stroke-width="4" stroke-linecap="round"/>`)
  content.push(`<ellipse cx="${centerX - 8}" cy="${centerY + 6}" rx="10" ry="5" fill="#7faa67" transform="rotate(-28 ${centerX - 8} ${centerY + 6})"/>`)
  content.push(`<ellipse cx="${centerX + 9}" cy="${centerY + 3}" rx="10" ry="5" fill="#8fbb73" transform="rotate(28 ${centerX + 9} ${centerY + 3})"/>`)
  content.push(`<ellipse cx="${centerX}" cy="${centerY - 15}" rx="9" ry="14" fill="${palette.primary}"/>`)
  content.push(`<ellipse cx="${centerX - 13}" cy="${centerY - 4}" rx="9" ry="14" fill="${palette.secondary}" transform="rotate(-52 ${centerX - 13} ${centerY - 4})"/>`)
  content.push(`<ellipse cx="${centerX + 13}" cy="${centerY - 4}" rx="9" ry="14" fill="${palette.secondary}" transform="rotate(52 ${centerX + 13} ${centerY - 4})"/>`)
  content.push(`<circle cx="${centerX}" cy="${centerY - 5}" r="7" fill="${palette.center}"/>`)
  if (plot.iconUrl) {
    content.push(`<image x="${x + 4}" y="${y + 4}" width="${size - 8}" height="${size - 8}" preserveAspectRatio="xMidYMid meet" href="${escapeXml(plot.iconUrl)}"/>`)
  } else {
    content.push(`<text x="${centerX}" y="${y + size - 7}" font-size="10" font-family="${FONT_FAMILY}" fill="#6d765e" font-weight="800" text-anchor="middle">${progress}%</text>`)
  }
}

function getPlantPalette(plot: HomePlot, ripe: boolean) {
  const palettes = [
    { primary: '#f4d35e', secondary: '#f7b267', center: '#8a5a2b' },
    { primary: '#f4978e', secondary: '#fbc4ab', center: '#9a3f3f' },
    { primary: '#b8e0d2', secondary: '#95b8d1', center: '#33658a' },
    { primary: '#cdb4db', secondary: '#ffc8dd', center: '#7b2cbf' },
    { primary: '#f6bd60', secondary: '#84a59d', center: '#5f6f52' },
  ]
  if (ripe) return palettes[0]
  const index = plot.seedId ? Math.abs(plot.seedId) % palettes.length : 2
  return palettes[index]
}

function renderSectionTitle(content: string[], y: number, title: string, subtitle: string) {
  content.push(`<text x="${PADDING_X}" y="${y}" font-size="22" font-family="${FONT_FAMILY}" fill="#2f3f31" font-weight="800">${escapeXml(title)}</text>`)
  content.push(`<text x="${WIDTH - PADDING_X}" y="${y}" font-size="15" font-family="${FONT_FAMILY}" fill="#7c856f" text-anchor="end">${escapeXml(subtitle)}</text>`)
  return y + 18
}

function renderNotice(content: string[], y: number, warning: string) {
  content.push(`<rect x="${PADDING_X}" y="${y}" width="${WIDTH - PADDING_X * 2}" height="52" rx="16" fill="#fff4df" stroke="#e2bd73"/>`)
  content.push(`<text x="${PADDING_X + 18}" y="${y + 32}" font-size="15" font-family="${FONT_FAMILY}" fill="#8f5b1e">${escapeXml(truncate(warning, 58))}</text>`)
  return y + 72
}

function formatPet(pet: HomePet) {
  return pet.name || '未知精灵'
}

function isPlotRipe(plot: HomePlot) {
  return Boolean(plot.ripTime && plot.ripTime <= Math.floor(Date.now() / 1000))
}

function getPetInspiration(pet: HomePet) {
  if (pet.status === 1704) {
    return { label: '守护中', progress: 0 }
  }

  if (!pet.inspirationReadyAt) {
    return { label: '灵感时间未知', progress: 0 }
  }

  const now = Math.floor(Date.now() / 1000)
  const remain = pet.inspirationReadyAt - now
  if (remain <= 0) {
    return { label: '灵感已可收集', progress: 100 }
  }

  const progress = pet.inspirationDuration
    ? clampPercent((1 - remain / pet.inspirationDuration) * 100)
    : 50
  return {
    label: `灵感收集中 - ${formatDurationSeconds(remain)}`,
    progress,
  }
}

function getPlotProgress(plot: HomePlot) {
  if (isPlotRipe(plot)) return 100
  if (!plot.ripTime) return 0
  if (!plot.growDuration) return 40

  const now = Math.floor(Date.now() / 1000)
  const remain = Math.max(0, plot.ripTime - now)
  return clampPercent((1 - remain / plot.growDuration) * 100)
}

function formatPlotRemain(plot: HomePlot) {
  if (!plot.ripTime) return '成熟时间未知'
  const remain = plot.ripTime - Math.floor(Date.now() / 1000)
  if (remain <= 0) return '已成熟'
  return `${formatDurationSeconds(remain)}后成熟`
}

function formatDurationSeconds(seconds: number) {
  const hour = Math.floor(seconds / 3600)
  const minute = Math.floor((seconds % 3600) / 60)
  const second = seconds % 60
  if (hour) return `${hour}时${minute}分`
  if (minute) return `${minute}分${second}秒`
  return `${second}秒`
}

function formatGenderText(gender: number | undefined) {
  if (gender === 1) return '♂ 雄性'
  if (gender === 2) return '♀ 雌性'
  return ''
}

function formatMutation(pet: HomePet) {
  if (pet.mutationName && pet.mutationName !== '普通') return pet.mutationName
  if (pet.mutationType === 1) return '异色'
  if (pet.mutationType === 8) return '炫彩'
  if (pet.mutationType === 9) return '异色炫彩'
  return ''
}

function formatValue(value: unknown, prefix = '') {
  if (value == null || value === '') return '未知'
  return `${prefix}${value}`
}

function formatNumber(value: number | undefined) {
  return typeof value === 'number' ? value.toLocaleString('zh-CN') : '未知'
}

function formatUnknown(value: unknown) {
  return value == null || value === '' ? '未知' : String(value)
}

function formatOrigin(origin: HomeQueryResult['origin']) {
  if (origin === 'cache') return '短缓存'
  if (origin === 'stale') return '旧缓存回退'
  return '实时请求'
}

function clampPercent(value: number) {
  if (!Number.isFinite(value)) return 0
  return Math.max(0, Math.min(100, Math.round(value)))
}

function truncate(text: string, maxLength: number) {
  return text.length > maxLength ? `${text.slice(0, maxLength - 1)}…` : text
}

function escapeXml(text: string) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

const FONT_FAMILY = 'Microsoft YaHei, PingFang SC, Noto Sans CJK SC, Arial'
