import { MerchantData, SourceName } from '../types'
import { formatDateTime } from '../utils/time'

export type ItemIconMap = Record<string, string>

export function renderSvgImage(
  data: MerchantData,
  source: SourceName,
  timezoneOffset: number,
  itemIcons: ItemIconMap = {},
) {
  const items = Array.isArray(data.items) ? data.items : []
  const width = 900
  const headerHeight = 130
  const cardHeight = 92
  const cardGap = 16
  const footerHeight = 32
  const height = headerHeight + footerHeight + items.length * (cardHeight + cardGap) + 40

  const content: string[] = []
  content.push(`<rect width="${width}" height="${height}" rx="24" fill="#f6f1df"/>`)
  content.push(`<rect x="0" y="0" width="${width}" height="${headerHeight}" rx="24" fill="#4a7a45"/>`)
  content.push(`<text x="40" y="52" font-size="28" font-family="Microsoft YaHei, Arial" fill="#ffffff" font-weight="700">${escapeXml(data.merchant_name || '远行商人')}</text>`)
  content.push(`<text x="40" y="88" font-size="16" font-family="Microsoft YaHei, Arial" fill="#eaf4df">${escapeXml(data.subtitle || '')}</text>`)
  content.push(`<text x="520" y="52" font-size="16" font-family="Microsoft YaHei, Arial" fill="#eaf4df">数据源：${escapeXml(formatSource(source))}</text>`)
  content.push(`<text x="520" y="82" font-size="16" font-family="Microsoft YaHei, Arial" fill="#eaf4df">抓取时间：${escapeXml(formatDateTime(data.fetched_at || Date.now(), timezoneOffset))}</text>`)

  if (data.round) {
    const roundText = [data.round.label, data.round.status ? `状态：${data.round.status}` : '', data.round.countdown ? `倒计时：${data.round.countdown}` : '']
      .filter(Boolean)
      .join(' | ')
    content.push(`<text x="40" y="118" font-size="16" font-family="Microsoft YaHei, Arial" fill="#eaf4df">${escapeXml(roundText)}</text>`)
  }

  items.forEach((item, index) => {
    const y = headerHeight + 24 + index * (cardHeight + cardGap)
    const iconX = 52
    const iconY = y + 14
    const iconSize = 64
    const textX = 136
    const iconKey = item.image || `${index}`
    const iconHref = itemIcons[iconKey]
    const iconLabel = escapeXml((item.name || '?').slice(0, 1))

    content.push(`<rect x="28" y="${y}" width="${width - 56}" height="${cardHeight}" rx="18" fill="#fffdf6" stroke="#d7cfb5"/>`)
    content.push(`<rect x="${iconX}" y="${iconY}" width="${iconSize}" height="${iconSize}" rx="14" fill="#f2ecd8" stroke="#d8ceb1"/>`)
    if (iconHref) {
      content.push(`<image x="${iconX}" y="${iconY}" width="${iconSize}" height="${iconSize}" preserveAspectRatio="xMidYMid slice" href="${escapeXml(iconHref)}"/>`)
    } else {
      content.push(`<text x="${iconX + 18}" y="${iconY + 42}" font-size="28" font-family="Microsoft YaHei, Arial" fill="#8a7d58" font-weight="700">${iconLabel}</text>`)
    }
    content.push(`<text x="${textX}" y="${y + 34}" font-size="22" font-family="Microsoft YaHei, Arial" fill="#2f392f" font-weight="700">${escapeXml(`${index + 1}. ${item.name || '未知商品'}`)}</text>`)

    const detailLeft = [item.kind ? `类型：${item.kind}` : '', typeof item.limit === 'number' ? `限购：${item.limit}` : '', item.time_label ? `时段：${item.time_label}` : '']
      .filter(Boolean)
      .join('  ')
    const detailRight = [typeof item.price === 'number' ? `价格：${item.price.toLocaleString('zh-CN')}` : '', item.countdown ? `剩余：${item.countdown}` : '']
      .filter(Boolean)
      .join('  ')

    content.push(`<text x="${textX}" y="${y + 64}" font-size="16" font-family="Microsoft YaHei, Arial" fill="#5f695f">${escapeXml(detailLeft)}</text>`)
    content.push(`<text x="${textX}" y="${y + 84}" font-size="16" font-family="Microsoft YaHei, Arial" fill="#9d6b2f">${escapeXml(detailRight)}</text>`)
  })

  content.push(`<text x="40" y="${height - 16}" font-size="14" font-family="Microsoft YaHei, Arial" fill="#707070">Generated by koishi-plugin-roco-world-merchant</text>`)

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
${content.join('\n')}
</svg>`
}

function formatSource(source: SourceName) {
  return source === 'onebiji' ? 'onebiji 主源' : '咸鱼备用源'
}

function escapeXml(text: string) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}
